### PR TITLE
Fix badger dep (again) and update options code

### PR DESCRIPTION
**Pull request by cap10morgan**
[Badger has reverted their shift to go modules `/v2` versioning](https://github.com/dgraph-io/badger/commit/04ca2be881736c7f2145afed448e11ad2f13fe01). There is some talk of un-reverting (re-re-reverting?), but for now the build is broken again. This PR seems to fix it.

### CODE REVIEW

**Comment by cap10morgan** [comment]
The CI build might need a `go clean -modcache` or `env GOPROXY='https://proxy.golang.org' go clean -modcache` to clear out the old `badger/v2` stuff.

**Comment by Kubuxu** [comment]
I've cleaned badger test.
Can you update it to `@master` instead of `@latest` tag. I don't want to depend on the `-rc2` tag which is inconsistent between github and `proxy.golang.org`.

**Comment by campoy** [comment]
Please do not merge this, as you will end up depending on a release candidate.

You should be able to simply depend on v1.5.5 and you won't need to change anything compared to the tag `v2.0.0-rc.2` which you were depending on.

As I explained on https://github.com/dgraph-io/badger/issues/904 this tag was never supposed to exist, and I mistakenly thought no one would depend on.

**Comment by campoy** [comment]
I'm happy to send a PR myself, give me a minute.

**Comment by Kubuxu** [comment]
@campoy it will be hard for us to downgrade as we have already packages that use the newly broken 2.0.0-rc2. 

This would mean that we have to walk through all of our uses of badger and upgrade it so we don't depend on 2.0.0-rc2. It would be much easier if you were to release `-rc3` so we don't have to do downgrading.

**Comment by Kubuxu** [comment]
On the other hand we can also upgrade all go-ds-badger uses, it isn't that many.

**Comment by campoy** [comment]
You are then migrating to v2.0.0 which will use a different file format to the one you're currently using.

I can't stop you from doing so, but please be aware that you are jumping from ~v1.5.3 to v2.0.0.
This is not a backward-compatible change neither on API or data format on disk, so users that already have badger databases stored in disks will not be able to open them with this new version.

Please reconsider this and migrate to v1.5.5, or v1.6.0 which should be released next week.
I'm happy to tag v1.6.0-rc1 right away so you can depend on it, but please do not use v2 before we actually release it.

**Comment by Kubuxu** [comment]
Ahh, I was not aware that v2 was changing disk data format. I was under impression that on-disk format was defined stable a while ago.

OK. We will downgrade.

**Comment by campoy** [comment]
Just give me a minute and I'll send a PR, sorry again about all this mess.

**Comment by Kubuxu** [comment]
Thanks!

**Comment by campoy** [comment]
Sent #65

**Pull request closed without merging**
